language: node_js
node_js:
- node
cache: npm
script: npm run deploy
after_script: npm run alias
env:
  global:
    secure: GE3AH8jO07BTktn6g7EGBtTo6W5CKXuBfDgBdfvzBM2EV9BLwpC6t/MiNx055eRF66leBSQkgr7OREor/gjQhz6bAyDTQYOpokupDQ4z86Q+qRcJ80b4rjJEi/7cnUgazQVROYuhAFRqhBmwhBedcE31J0YgrPkZpQXyTDOiaiGblnxTzp6RheDA5ni23amQhE6op3fAFqqcXU13pxAdiu82ez2WoKu0UXnTMx0fRp9BiEQc9DWqFNbXJ6qSsQ1UBUnn9YUDr6ac+xrR36J1w5iE0tr++xlLjlgiWjsBnPSAdGXjLFFyKKIjQVvqExmSWlcxw1iSs7+t8kt45p1iGc0pSuF0pua5Xvpgv4CPsm12WZU7ocTSM9ZlEt6/HOCOqvibHpviG1/TF3cwXeoUfI6eFdHU58IB1gLVIlgXuEZateVQk2kIJeyKxomB7lBPz1Tf3sHaLPwJ8eCZoI/JKXLv54xonhrF8KFIv4LCza/DROoLlBzAqrkGuX37B+pek7TrW6Xicw/HcoiUYaJbUNjIEmDb1Kg3YBY7q+KKX1tC0HP3qYIs9IUbgl5ibb1VSOXAXYXR0Msa7tHIhpB1LGDs46f4twI+TrIukjB80G05jNScnny/NdvFkuUeAClgr7dTt89pPmsT7AnD3uKdZmxaz1+R4Mxv83itLkO2hwA=
